print("I like Hockey")
print("I like Baseball")
print("I like Burgers")
print("I like Nba 2k20")
print("I like Minecraft")
print("I like hanging out with friends")
print("I like sleeping")
print("I like rap music")